### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by AlenMiletic** [AlenMiletic/Tentamen---praksa#8]
Proci kroz https://www.codecademy.com/tracks/ruby tutorial.

**Comment by AlenMiletic** [comment]
1. Introduction to Ruby napravljeno.

**Comment by AlenMiletic** [comment]
2. Control Flow in Ruby napravljeno

**Comment by AlenMiletic** [comment]
3. Looping with Ruby napravljeno

**Comment by AlenMiletic** [comment]
4. Data Structures napravljeno

**Comment by karlosmid** [comment]
@AlenMiletic Zadatak. Za polje cijelih brojeva od 1 do 10, ako je broj paran, ispisi Paran, a ako je neparan, ispisi Neparan.

**Comment by AlenMiletic** [comment]
5. Methods, Blocks, & Sorting napravljeno

**Comment by AlenMiletic** [comment]
6. Hashes and Symbols napravljeno

**Comment by AlenMiletic** [comment]
7. Refactoring napravljeno

**Comment by AlenMiletic** [comment]
8. Blocks, Procs and Lambdas napravljeno.

**Comment by AlenMiletic** [comment]
9. Object - Oriented Programming part 1. napravljeno.

**Comment by AlenMiletic** [comment]
10. Object - Oriented Programming part 2. napravljeno.
