### ISSUE TITLE
1. Zadatak Ruby

### ISSUE THREAD

**Issue by AlenMiletic** [AlenMiletic/Tentamen---praksa#9]
Zadatak. Za polje cijelih brojeva od 1 do 10, ako je broj paran, ispisi Paran, a ako je neparan, ispisi Neparan.

**Comment by AlenMiletic** [comment]
Riješenje:

```
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

numbers.each { |x|
  if (x % 2 == 0)
    puts "Broj #{x} je paran."
    else 
    puts "Broj #{x} je neparan."
  end
  }
```

**Comment by karlosmid** [comment]
- [ ] Napraviti granu zadatak_1
- [ ] u nju dodati zadatak_1.rb rjesenje prethodnog zadatka
- [ ] napraviti pull request u master granu, dodati mene kao review
- [ ] ja cu potvrditi merge.
